version: 3

tasks:
  setup-qwik:
    run: once
    dir: ./qwik
    cmds:
      - pnpm install
    sources:
      - package.json
    generates:
      - node_modules
  build-qwik:
    run: once
    deps: [setup-qwik]
    dir: ./qwik
    cmds:
      - pnpm build.core
    sources:
      - packages/qwik/src/**
      - packages/qwik-router/src/**
    generates:
      - packages/qwik/dist
      - packages/qwik-router/dist
  install-original:
    deps: [build-qwik]
    dir: ./project-original
    cmds:
      - pnpm i
    sources:
      - package.json
    generates:
      - node_modules
  install-new:
    deps: [build-qwik]
    dir: ./project-new
    cmds:
      - pnpm i
    sources:
      - package.json
    generates:
      - node_modules
  build-original:
    deps: [install-original]
    dir: ./project-original
    cmds:
      - pnpm run build
    sources:
      - ./**/*.ts
      - ./**/*.tsx
      - ./**/*.css
    generates:
      - dist
  build-new:
    deps: [install-new]
    dir: ./project-new
    cmds:
      - pnpm run build
    sources:
      - ./**/*.ts
      - ./**/*.tsx
      - ./**/*.css
    generates:
      - dist
  diff-builds:
    deps: [build-original, build-new]
    cmds:
      - diff -bur ./project-original/dist ./project-new/dist
  clean:
    cmds:
      - rm -rf ./project-original/dist ./project-new/dist
