version: 3

tasks:
  setup-qwik:
    run: once
    dir: ./qwik
    cmds:
      - pnpm install
    sources:
      - package.json
    generates:
      - node_modules
  build-qwik:
    run: once
    deps: [setup-qwik]
    dir: ./qwik
    cmds:
      - pnpm build.core
    sources:
      - packages/qwik/src/**
      - packages/qwik-router/src/**
    generates:
      - packages/qwik/dist
      - packages/qwik-router/dist
  setup-qwik2:
    run: once
    dir: ./qwik2
    cmds:
      - cp ../Cargo.toml.patched ./Cargo.toml
      - cp ../binding-platform.ts.patched ./scripts/binding-platform.ts
      - cp ../rust-toolchain.patched ./rust-toolchain
      - ln -sf ../qwik-optimizer .
      - pnpm install
    sources:
      - package.json
    generates:
      - node_modules
      - qwik-optimizer
  build-qwik2:
    run: once
    deps: [setup-qwik2]
    dir: ./qwik2
    cmds:
      - pnpm build.core
    sources:
      - packages/qwik/src/**
      - packages/qwik-router/src/**
      - qwik-optimizer/napi/src/**
      - qwik-optimizer/optimizer/src/**
    generates:
      - packages/qwik/dist
      - packages/qwik-router/dist
  install-original:
    deps: [build-qwik]
    dir: ./project-original
    cmds:
      - pnpm i
    sources:
      - package.json
    generates:
      - node_modules
  install-new:
    deps: [build-qwik2]
    dir: ./project-new
    cmds:
      - pnpm i
    sources:
      - package.json
    generates:
      - node_modules
  build-original:
    deps: [install-original]
    dir: ./project-original
    cmds:
      - pnpm run build
    sources:
      - ./**/*.ts
      - ./**/*.tsx
      - ./**/*.css
    generates:
      - dist
  build-new:
    deps: [install-new]
    dir: ./project-new
    cmds:
      - pnpm run build
    sources:
      - ./**/*.ts
      - ./**/*.tsx
      - ./**/*.css
    generates:
      - dist
  diff-builds:
    deps: [build-original, build-new]
    cmds:
      - diff -bur ./project-original/dist ./project-new/dist
  clean:
    cmds:
      - rm -rf ./project-original/dist ./project-new/dist
